<a href="https://colab.research.google.com/github/RoksanaMaya/OpenCV/blob/main/digit_recognition3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import cv2
import numpy as np
import os
from matplotlib import pyplot as plt
%matplotlib inline

In [16]:
path='/content/drive/MyDrive/Colab Notebooks/OpenCV/'

In [17]:
def imread(path):
    image = plt.imread(path, cv2.IMREAD_UNCHANGED)
    return image

In [18]:
def resize_image (image):
    resize=cv2.resize(image,(1000,1000))
    return resize

## Reading 0

In [19]:

image=cv2.imread(path+"0.png",0)
resize=resize_image (image)
image.shape, resize.shape

((1200, 1200), (1000, 1000))

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [20]:
print(np.array(image))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [21]:
print(np.array(resize))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


## Reading 1


In [22]:
image=cv2.imread(path+"1.png",0)
resize=resize_image (image)
#grayscale_image = cv2.cvtColor(resize, cv2.COLOR_BGR2GRAY)
image.shape, resize.shape

((360, 360), (1000, 1000))

In [23]:
image1=np.array(image)
print(image1)

[[255 255 255 ... 238 238 238]
 [255 255 255 ... 238 238 238]
 [255 255 255 ... 238 238 238]
 ...
 [238 238 238 ... 255 255 255]
 [238 238 238 ... 255 255 255]
 [238 238 238 ... 255 255 255]]


In [24]:
image1=np.array(resize)
print(image1)

[[255 255 255 ... 238 238 238]
 [255 255 255 ... 238 238 238]
 [255 255 255 ... 238 238 238]
 ...
 [238 238 238 ... 255 255 255]
 [238 238 238 ... 255 255 255]
 [238 238 238 ... 255 255 255]]


In [25]:
image=cv2.imread(path+"0.png",0)
resize=resize_image (image)

image.shape, resize.shape

((1200, 1200), (1000, 1000))

In [26]:
print(np.array(image))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [27]:
image1=np.array(resize)
print(np.array(resize))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
